### ISSUE TITLE
Error after installing the plugin and enabling it！

### ISSUE THREAD

**Issue by chenpaner** [semagnum/blint#19]
Blender3.6/BLint-0.31
Traceback (most recent call last):
  File "G:\Blender Program\stable\blender-3.6.0-windows-x64\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\BLint\__init__.py", line 64, in register
    model.register()
  File "G:\Blender Program\stable\blender-3.6.0-windows-x64\3.6\scripts\modules\bpy\utils\__init__.py", line 744, in register
    register_class(cls)
ValueError: register_class(...): already registered as a subclass 'LintIssue'

**Comment by semagnum** [comment]
Hey chenpaner. Is this your first time using BLint, or an upgrade from a previous version? If that latter, make sure to unregister the previous version, close and restart Blender, and then install the new version. Python will still keep the previous version even after unregistering, so closing Blender is needed to clear it (this is typical of most add-ons).

**Comment by chenpaner** [comment]
This is my first time using BLin！

**Comment by semagnum** [comment]
Thank you. I was able to reproduce on my end. It wasn't from the error you gave me, as yours was from re-checking the box. There was an initial error before that. But I updated the [0.3.1](https://github.com/semagnum/blint/releases/tag/0.3.1) release with a zip that works on my end.

**Comment by semagnum** [comment]
Closing after no response and fix validated on my end.
